name: Publish a new version

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get the version
        id: get_version
        uses: SebRollen/toml-action@v1.0.1
        with:
          file: 'pyproject.toml'
          field: 'tool.poetry.version'

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            nebulabroadcast/nebula-worker:dev

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.get_version.outputs.value }}
          name: Nebula worker ${{ steps.get_version.outputs.value }}
          body: Nebula worker version ${{ steps.get_version.outputs.value }}
          allowUpdates: true
          draft: true
          prerelease: false
